on:
  push:
    branches: [main]

name: get jira version tag
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: prashant-demo110
          repo: release_management_poc
      - name: Example of consumption of the output
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
        run: |
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          Release_name=$(echo "$release_json" | jq -r '.[0].name')
          Body=$(echo "$release_json" | jq -r '.[0].body')
          Released_date=$(echo "$release_json" | jq -r '.[0].published_at')
          Commit_branch_name=$(echo "$release_json" | jq -r '.[0].target_commitish')
          echo "Release_tag: Latest Tag is : $Release_tag"
          echo "Release_name: Latest Release Tag Name is : $Release_name"
          echo "Body: Latest Release Tag Body is : $Body"
          echo "Released_date: Timings are : $Released_date"
          echo "Commit_branch_name: Branch triggered : $Commit_branch_name"
