on:
  push:
    branches: [main]
       
name: get jira version tag
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: prashant-demo110
          repo:  release_management_poc
      - name: Example of consumption of the output
        env:
          LATEST_TAG: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
        run: |
            echo "Version $LATEST_TAG was released with release name as - $LATEST_DATE
            release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
            latest_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
            latest_release=$(echo "$release_json" | jq -r '.[0].releaseName')
            latest_tag_published_at=$(echo "$release_json" | jq -r '.[0].published_at')
            target_commitish=$(echo "$release_json" | jq -r '.[0].target_commitish')

            echo "latest_tag: $latest_tag"
            echo "latest_release: $latest_release"
            echo "latest_tag_published_at: $latest_tag_published_at"
            echo "target_commitish: $target_commitish"

            echo ::set-output name=latest_tag::"$latest_tag"
            echo ::set-output name=latest_release::"$latest_release"
            echo ::set-output name=latest_tag_published_at::"$latest_tag_published_at"
            echo ::set-output name=target_commitish::"$target_commitish"
