on:
  push:
    branches: [main]

name: get jira version tag
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://prashantb02.atlassian.net
          JIRA_USER_EMAIL: pulkit155rkgit@gmail.com
          JIRA_API_TOKEN: ${{secrets.PULKIT}}


      - name: Example of consumption of the output
        run: |
          owner="prashant-demo110"
          repo="release_management_poc"
          project_name="HP"
          host_url="prashantb02.atlassian.net"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          Release_name=$(echo "$release_json" | jq -r '.[0].name')
          Body=$(echo "$release_json" | jq -r '.[0].body')
          Released_date=$(echo "$release_json" | jq -r '.[0].published_at')
          Commit_branch_name=$(echo "$release_json" | jq -r '.[0].target_commitish')


          echo "Release_tag: Latest Tag is : $Release_tag"
          echo "Release_name: Latest Release Tag Name is : $Release_name"
          echo "Body: Latest Release Tag Body is : $Body"
          echo "Released_date: Timings are : $Released_date"
          echo "Commit_branch_name: Branch triggered : $Commit_branch_name"

          echo ::set-output name=Release_tag::"$Release_tag"
          echo ::set-output name=Release_name::"$Release_name"
          echo ::set-output name=Body::"$Body"
          echo ::set-output name=Released_date::"$Released_date"
          echo ::set-output name=Commit_branch_name::"$Commit_branch_name"
          
          curl -X POST -H 'Content-type: application/json' --data "fixversion":"v9.9.9" https://automation.atlassian.com/pro/hooks/0539d97c488d25b325d53db2f4b0ff75d57520db?issue=RD-5
