name: Jira Release Management
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Jira Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://prashantb02.atlassian.net
        JIRA_USER_EMAIL: pulkit155rkgit@gmail.com
        JIRA_API_TOKEN: ${{secrets.PULKIT}}
#    steps:
#    - name: Release
#      uses: fnkr/github-action-ghr@v1
#      if: startsWith(github.ref, 'refs/tags/')
#      env:
#        GHR_COMPRESS: xz
#        GHR_PATH: build/
#        GITHUB_TOKEN: ${{ secrets.P_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # need this for all history for all branches and tags
      - name: Create Release
        id: create_release
        uses: nickatnight/releases-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.P_Token }}

    outputs:
      ReleaseTag: ${{ steps.create_release.outputs.release_tag }}

  # pass in as env variable
  explore-essos:
    runs-on: ubuntu-latest
    needs: [create-release]
    env:
      RELEASE_TAG: ${{ needs.create-release.outputs.ReleaseTag }}
